### ISSUE TITLE
No video widget in windows 10

### ISSUE THREAD

**Issue by Nachesko** [hologfx/holographics-issues#32]
Hi, I´m not seeing the video widget or the youtube widget under windows 10, I have two instances in different computers, clean install, both in 1.11.0, stable channel. They are in the user_data\widgets directory. Already resetted default widgets
![holo](https://user-images.githubusercontent.com/86963277/124469677-07fd0f00-dd71-11eb-8f64-26b8373f7d5d.PNG)

**Comment by paolohu** [comment]
Same for me on a Mac - v1.11.0.  If I change the category on the index.js for the widget from "Video" to "Utility" then they show up.

**Comment by florisporro** [comment]
Try the new build on the alpha channel, it should have this problem fixed.

**Comment by paolohu** [comment]
yep - that version fixes it

**Comment by florisporro** [comment]
Now fixed in v1.11.1
